#pragma once
#define _CRT_SECURE_NO_WARNINGS
#include <iostream>
#include <iomanip>
#include <stdio.h>
#include <conio.h>
#include <cmath>
#include <ctime>
#include <Windows.h>
#include <string>
#include <stdlib.h>
#include <fstream>
#include <tchar.h>